[package]
name = "document-extraction"
version = "0.0.0"
edition = "2021"

[dependencies]
lopdf = "0.38.0"
moenarch-image-analysis-ocr = { git = "https://github.com/moritzbrantner/visual-analysis", rev = "e683c365ae4f736ea389258fe6a6683849dd3edc" }
serde = { version = "1", features = ["derive"] }
thiserror = "2"

[dev-dependencies]
serde_json = "1"
